const USER_STATUS = {
  PENDING: 'PENDING',
  ACTIVE: 'ACTIVE',
  SUSPENDED: 'SUSPENDED',
};

const USER_ROLE = {
  USER: 'USER',
  ADMIN: 'ADMIN',
};

const AUTH_ACTION = {
  REGISTER: 'REGISTER',
  OTP_GENERATED: 'OTP_GENERATED',
  OTP_RESENT: 'OTP_RESENT',
  OTP_VERIFIED: 'OTP_VERIFIED',
  OTP_FAILED: 'OTP_FAILED',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILED: 'LOGIN_FAILED',
  REFRESH_SUCCESS: 'REFRESH_SUCCESS',
  REFRESH_FAILED: 'REFRESH_FAILED',
  LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
  LOGOUT_FAILED: 'LOGOUT_FAILED',
  PASSWORD_CHANGED: 'PASSWORD_CHANGED',
};

module.exports = {
  USER_STATUS,
  USER_ROLE,
  AUTH_ACTION,
};
